services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: paintings_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paintings_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AWS_REGION: eu-north-1
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
